name: CI

on: [pull_request, push]

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo 'NODE_OPTIONS="--openssl-legacy-provider"' >> $GITHUB_ENV
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Report Compressed Size
        uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: index.js
